version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB_NAME=$MYSQL_DB_NAME 
      - APP_KEY=super_strok_key_no1_quezzes_it
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
  
  scheduler:
    image: node
    container_name: node-scheduler
    restart: always
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB_NAME=$MYSQL_DB_NAME 
      - APP_KEY=super_strok_key_no1_quezzes_it
    volumes:
      - .:/home/node/app
    command: "node ace scheduler:run"
      
  db:
   image: mysql:5.7
   restart: unless-stopped
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
     - MYSQL_DATABASE=$MYSQL_DB_NAME
   ports:
     - 3307:3306
   volumes:
     - db:/var/lib/mysql

volumes:
  db: